# -*- coding: utf-8 -*-
# Part of BrowseInfo. See LICENSE file for full copyright and licensing details.
{
    'name': 'All in One Inventory Report Management',
    'version': '19.0.0.0',
    'category': 'Warehouse',
    'summary': 'All in one stock reports all in one warehouse reports inventory turnover analysis report stock inventory valuation report stock valuation report product overstock report inventory coverage report inventory age breakdown report warehouse stock movement report',
    'description': """
        All in One Inventory Report Management Odoo Apps for various reports to cover all important stock information.User can generate different inventory and warehouse reports like Real-Time Inventory Valuation Report, Stock Expiry Report, Warehouse Out of Stock Analysis Report, Inventory Coverage Report, Warehouse Turnover Analysis Report, Stock Age Breakdown XLS Report, Stock Age Analysis Report, Warehouse Overstock Analysis Report, FSN XYZ Analysis Report, ABC Analysis Report, Warehouse Stock Rotation Analysis Excel Report, Export Stock In Excel Report in Odoo Warehouse ERP.
    """,
    'author': 'quadra',
    'website': 'https://www.browseinfo.com/demo-request?app=bi_all_inventory_analysis_reports&version=17&edition=Community',
    'depends': ['base', 'stock', 'purchase','sale_management','product_expiry'],
    'data': [
        'security/ir.model.access.csv',
        'reports/export_stock_info_report.xml',
        'reports/export_stock_info_templates.xml',
        'reports/inventory_coverage_template.xml',
        'reports/inventory_overstock_template.xml',
        'reports/inventory_valuation_reports_report.xml',
        'reports/inventory_valuation_reports_report_template.xml',
        'reports/report_stock_expiry_template.xml',
        'reports/report_stock_expiry_template_all.xml',
        'reports/report_stock_expiry_template_location.xml',
        'reports/report_stock_expiry_template_warehouse.xml',
        'reports/stock_expiry_report.xml',
        'reports/stock_report.xml',
        # 'data/mail_templates.xml',
        'wizard/bi_abc_analysis_report_view.xml',
        'wizard/bi_age_breakdown_report_view.xml',
        'wizard/bi_age_report_view.xml',
        'wizard/bi_fsn_xyz_report_view.xml',
        'wizard/bi_stockrotation_report_view.xml',
        'wizard/bi_turnover_report_view.xml',
        'wizard/export_stock_info_view.xml',
        'wizard/inventory_Coverage_wizard_view.xml',
        'wizard/bi_overstock_report_view.xml',
        'wizard/inventory_overstock_wizard_view.xml',
        'wizard/inventory_valuation_reports_wizard.xml',
        'wizard/non_moving_view_wizard.xml',
        'wizard/outofstock_report_wizard.xml',
        'wizard/product_recommendation_view.xml',
        'wizard/stock_expiry_report_wizard.xml',
        'wizard/stock_rotation_wizard_view.xml',
        'views/stock_config_settings.xml',
        'views/report_menuitems.xml',
    ],
    'license':'OPL-1',
    'installable': True,
    'auto_install': False,
    'live_test_url':'https://www.browseinfo.com/demo-request?app=bi_all_inventory_analysis_reports&version=17&edition=Community',
    "images":['static/description/Banner.gif'],
}
