from . import amazon_api
from . import amazon_sync_log
from . import amazon_instance
from . import amazon_product
from . import amazon_sale_order
from . import amazon_settlement
from . import amazon_return
from . import amazon_removal_order
from . import amazon_inbound_shipment
from . import amazon_fba_inventory
from . import amazon_rating
from . import amazon_vcs
from . import amazon_outbound_order
from . import ai_pricing
from . import ai_listing
from . import ai_forecast
from . import ai_reviews
from . import amazon_product_health
from . import amazon_smart_alerts
from . import ai_profit_calculator
from . import res_config_settings
from . import sale_order_inherit
from . import stock_picking_inherit
from . import account_move_inherit
from . import amazon_user_guidance
